name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile binaries
        run: |
          deno compile --allow-run --allow-net -o dist/restarter-linux-x64 main.ts
          deno compile --allow-run --allow-net --target aarch64-unknown-linux-gnu -o dist/restarter-linux-arm64 main.ts
          deno compile --allow-run --allow-net --target x86_64-apple-darwin -o dist/restarter-macos-x64 main.ts
          deno compile --allow-run --allow-net --target aarch64-apple-darwin -o dist/restarter-macos-arm64 main.ts
          deno compile --allow-run --allow-net --target x86_64-pc-windows-msvc -o dist/restarter-windows-x64.exe main.ts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/restarter-linux-x64
            dist/restarter-linux-arm64
            dist/restarter-macos-x64
            dist/restarter-macos-arm64
            dist/restarter-windows-x64.exe 